### ISSUE TITLE
Project commits not in npm?

### ISSUE THREAD

**Issue by RandleBR** [sindresorhus/lpad#5]
Npm links this project to lpad, but it seems that the last couple commits are not published to npm? Is this intentional (new dependency on split-lines)?

**Comment by SamVerschueren** [comment]
Think @sindresorhus forgot about this. It should be a major release though as we ES2015ified the code and dropped support for older Node versions.

**Comment by sindresorhus** [comment]
No, it's intentional. I only do releases when there's an actual benefit for users. The changes after the last release makes no difference for the user. It's just refactoring with no performance improvement.
